### ISSUE TITLE
small-vector test failure when building with GCC 11

### ISSUE THREAD

**Issue by xvitaly** [eliaskosunen/scnlib#36] opened 2021-01-31 11:22 UTC
small-vector test failure when building with GCC 11.

GCC version 11.0.0.

Log:
```
+ /usr/bin/ctest --output-on-failure --force-new-ctest-process -j48
Test project /builddir/build/BUILD/scnlib-0.4/x86_64-redhat-linux-gnu
      Start  1: test
      Start  2: empty
      Start  3: util
      Start  4: small-vector
      Start  5: string-view
      Start  6: reader
      Start  7: range
      Start  8: locale
      Start  9: std-string-view
      Start 10: pmr-string
      Start 11: result
      Start 12: istream
      Start 13: tuple-return
      Start 14: char
      Start 15: integer
      Start 16: float
      Start 17: string
      Start 18: buffer
      Start 19: bool
      Start 20: usertype
      Start 21: list
      Start 22: each-integer
      Start 23: each-char
      Start 24: file
 1/24 Test  #1: test .............................   Passed    0.02 sec
 2/24 Test  #2: empty ............................   Passed    0.02 sec
 3/24 Test  #3: util .............................   Passed    0.02 sec
 4/24 Test  #5: string-view ......................   Passed    0.02 sec
 5/24 Test  #6: reader ...........................   Passed    0.02 sec
 6/24 Test  #7: range ............................   Passed    0.01 sec
 7/24 Test  #8: locale ...........................   Passed    0.01 sec
 8/24 Test  #9: std-string-view ..................   Passed    0.01 sec
 9/24 Test #10: pmr-string .......................   Passed    0.01 sec
10/24 Test #11: result ...........................   Passed    0.01 sec
11/24 Test #12: istream ..........................   Passed    0.01 sec
12/24 Test #13: tuple-return .....................   Passed    0.01 sec
13/24 Test #14: char .............................   Passed    0.01 sec
14/24 Test #15: integer ..........................   Passed    0.01 sec
15/24 Test #16: float ............................   Passed    0.01 sec
16/24 Test #17: string ...........................   Passed    0.01 sec
17/24 Test #18: buffer ...........................   Passed    0.01 sec
18/24 Test #19: bool .............................   Passed    0.01 sec
19/24 Test #20: usertype .........................   Passed    0.01 sec
20/24 Test #21: list .............................   Passed    0.01 sec
21/24 Test #23: each-char ........................   Passed    0.00 sec
22/24 Test #24: file .............................   Passed    0.00 sec
23/24 Test #22: each-integer .....................   Passed    0.07 sec
24/24 Test  #4: small-vector .....................Subprocess aborted***Exception:   0.10 sec
free(): invalid size
[doctest] doctest version is "2.4.4"
[doctest] run with "--help" for options
===============================================================================
../test/small_vector.cpp:263:
TEST CASE:  small_vector<signed char>
  size+value construct stack
../test/small_vector.cpp:97: ERROR: CHECK( vec.is_small() ) is NOT correct!
  values: CHECK( false )
../test/small_vector.cpp:99: ERROR: CHECK( vec.capacity() == 64 ) is NOT correct!
  values: CHECK( 3038287259199220266 == 64 )
===============================================================================
../test/small_vector.cpp:263:
TEST CASE:  small_vector<signed char>
  accessors stack
../test/small_vector.cpp:263: FATAL ERROR: test case CRASHED: SIGABRT - Abort (abnormal termination) signal
===============================================================================
../test/small_vector.cpp:263:
TEST CASE:  small_vector<signed char>
DEEPEST SUBCASE STACK REACHED (DIFFERENT FROM THE CURRENT ONE):
  accessors stack
===============================================================================
[doctest] test cases:  1 |  0 passed | 1 failed | 5 skipped
[doctest] assertions: 41 | 39 passed | 2 failed |
[doctest] Status: FAILURE!
96% tests passed, 1 tests failed out of 24
Total Test time (real) =   0.11 sec
The following tests FAILED:
	  4 - small-vector (Subprocess aborted)
```

**Comment by xvitaly** [comment] 2021-01-31 11:37
GCC 10.2.1:

```
Test project /builddir/build/BUILD/scnlib-0.4/x86_64-redhat-linux-gnu
      Start  1: test
      Start  2: empty
      Start  3: util
      Start  4: small-vector
      Start  5: string-view
      Start  6: reader
 1/24 Test  #1: test .............................   Passed    0.01 sec
      Start  7: range
 2/24 Test  #2: empty ............................   Passed    0.01 sec
      Start  8: locale
 3/24 Test  #3: util .............................   Passed    0.01 sec
      Start  9: std-string-view
 4/24 Test  #4: small-vector .....................   Passed    0.01 sec
      Start 10: pmr-string
 5/24 Test  #5: string-view ......................   Passed    0.01 sec
      Start 11: result
 6/24 Test  #6: reader ...........................   Passed    0.01 sec
      Start 12: istream
 7/24 Test  #7: range ............................   Passed    0.01 sec
      Start 13: tuple-return
 8/24 Test  #8: locale ...........................   Passed    0.01 sec
      Start 14: char
 9/24 Test  #9: std-string-view ..................   Passed    0.01 sec
      Start 15: integer
10/24 Test #10: pmr-string .......................   Passed    0.01 sec
      Start 16: float
11/24 Test #11: result ...........................   Passed    0.01 sec
      Start 17: string
12/24 Test #12: istream ..........................   Passed    0.01 sec
      Start 18: buffer
13/24 Test #13: tuple-return .....................   Passed    0.01 sec
      Start 19: bool
14/24 Test #14: char .............................   Passed    0.01 sec
      Start 20: usertype
15/24 Test #15: integer ..........................   Passed    0.01 sec
      Start 21: list
16/24 Test #16: float ............................   Passed    0.01 sec
      Start 22: each-integer
17/24 Test #17: string ...........................   Passed    0.01 sec
      Start 23: each-char
18/24 Test #18: buffer ...........................   Passed    0.01 sec
      Start 24: file
19/24 Test #19: bool .............................   Passed    0.01 sec
20/24 Test #20: usertype .........................   Passed    0.01 sec
21/24 Test #21: list .............................   Passed    0.01 sec
22/24 Test #23: each-char ........................   Passed    0.00 sec
23/24 Test #24: file .............................   Passed    0.00 sec
24/24 Test #22: each-integer .....................   Passed    0.06 sec
100% tests passed, 0 tests failed out of 24
```

**Comment by eliaskosunen** [comment] 2021-07-01 16:52
Unable to reproduce with g++ 11.1.0, seems like a compiler bug. Closing, but may reopen if reproducible.

**Closed by eliaskosunen** 2021-07-01 16:52 UTC
